entero   a    =   1   ;
entero   b    =   2   ;
si (  a < b     )
{
  a     =    3   ;
	mientras que (   a < b    )
	{
	   a    =    4   ;
	   a    =    5   ;
			si ( a =! b      )
			{
			
			  a     =   6    ;
			
			}
			sino
			{
			  a     =    7   ;
			repetir (  5     ) veces
			{
			
			   a    =    8   ;
			
			}
			}
   a    =    9   ;
	}
}
sino
{
   a    =    10   ;
	si (  a <= b     )
	{
	
	  a     =   11    ;
	
	}

}

















